Entitlements = [
  {entitlement: 'accelerometer'       , required_os: [3, 0], families_missing: %w()},
  {entitlement: 'armv6'               , required_os: [2, 0], families_missing: %w()},
  {entitlement: 'armv7'               , required_os: [3, 1], families_missing: %w(iPhone1 iPod1 iPod2)},
  {entitlement: 'auto-focus-camera'   , required_os: [3, 0], families_missing: %w(iPhone1 iPod1 iPod2 iPod3 iPod4 iPad1 iPad2)},
  {entitlement: 'bluetooth-le'        , required_os: [5, 0], families_missing: %w(iPhone1 iPhone2 iPhone3 iPod1 iPod2 iPod3 iPod4 iPad1 iPad2)},
  {entitlement: 'camera-flash'        , required_os: [3, 0], families_missing: %w(iPhone1 iPhone2 iPod1 iPod2 iPod3 iPod4 iPad)},
  {entitlement: 'front-facing-camera' , required_os: [3, 0], families_missing: %w(iPhone1 iPhone2 iPod1 iPod2 iPod3 iPad1)},
  {entitlement: 'gamekit'             , required_os: [4, 1], families_missing: %w(iPhone1,1 iPod1)},
  {entitlement: 'gps'                 , required_os: [3, 0], families_missing: %w(iPod)},
  {entitlement: 'gyroscope'           , required_os: [3, 0], families_missing: %w(iPhone1 iPhone2 iPod1 iPod2 iPod3 iPad1)},
  {entitlement: 'healthkit'           , required_os: [8, 0], families_missing: %w(iPhone1 iPhone2 iPhone3 iPod1 iPod2 iPod3 iPod4 iPad)},
  {entitlement: 'location-services'   , required_os: [3, 0], families_missing: %w()},
  {entitlement: 'magnetometer'        , required_os: [3, 0], families_missing: %w(iPod iPhone1)},
  {entitlement: 'metal'               , required_os: [8, 0], families_missing: %w(iPod1 iPod2 iPod3 iPod4 iPhone1 iPhone2 iPhone3 iPhone4 iPhone5 iPad1 iPad2 iPad3)},
  {entitlement: 'microphone'          , required_os: [3, 0], families_missing: %w(iPod1)},
  {entitlement: 'opengles-1'          , required_os: [3, 0], families_missing: %w()},
  {entitlement: 'opengles-2'          , required_os: [3, 0], families_missing: %w(iPod1 iPod2 iPhone1)},
  {entitlement: 'opengles-3'          , required_os: [7, 0], families_missing: %w(iPhone1 iPhone2 iPhone3 iPhone4 iPhone5 iPod1 iPod2 iPod3 iPod4 iPod5 iPad1 iPad2 iPad3)},
  {entitlement: 'peer-peer'           , required_os: [3, 1], families_missing: %w(iPod1 iPhone1,1)},
  {entitlement: 'sms'                 , required_os: [3, 0], families_missing: %w(iPod iPad)},
  {entitlement: 'still-camera'        , required_os: [3, 0], families_missing: %w(iPod1 iPod2 iPod3 iPad1)},
  {entitlement: 'telephony'           , required_os: [3, 0], families_missing: %w(iPod iPad)},
  {entitlement: 'video-camera'        , required_os: [3, 0], families_missing: %w(iPod1 iPod2 iPod3 iPhone1 iPad1)},
  {entitlement: 'wifi'                , required_os: [3, 0], families_missing: %w()},                                # TODO HANDLE IPHONE CHINA?!
].freeze
